name: epidemic-predictability
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - lightgbm>=4.0.0
  - pytorch>=2.0.0
  - scikit-learn>=1.2.0
  - pip
  - pip:
      - fitz
      - pymupdf
